import React from "react";
import { T, Ico, formatNGN, CTA, GhostBtn, RightPanel } from "./BuyFlowShared";

export default function BuyFlowStep3({
  payAmount, receiveAmount, selectedAsset, expiryTime, finalRate,
  paymentMethod, setPaymentMethod,
  nextStep, prevStep, breadcrumbs,
}) {
  const methods = [
    {
      key: "ngn_wallet",
      label: "NGN Wallet",
      sub: "Pay instantly from your Cheeseball balance",
      meta: "Instant delivery — crypto arrives immediately",
      Icon: Ico.wallet,
      iconBg: T.blueLight,
      iconColor: T.blue,
      badge: "Instant",
      badgeBg: T.greenLight,
      badgeColor: T.greenText,
    },
    {
      key: "paystack",
      label: "Paystack",
      sub: "Pay via virtual bank account generated by Paystack",
      meta: "Auto-detected — crypto sent once payment clears",
      Icon: Ico.paystack,
      iconBg: "#E0F2FE",
      iconColor: "#0BA4DB",
      badge: "Fast",
      badgeBg: "#ECFDF3",
      badgeColor: "#15803D",
    },
    {
      key: "bank_transfer",
      label: "Bank Transfer",
      sub: "Manual bank transfer with proof of payment",
      meta: "Review required — takes 1–24 hours",
      Icon: Ico.bank,
      iconBg: "#FFFBEB",
      iconColor: "#D97706",
      badge: "Manual",
      badgeBg: "#FFFBEB",
      badgeColor: "#B45309",
    },
  ];

  return (
    <div style={{display:"grid",gridTemplateColumns:"1fr 400px",minHeight:"100vh",background:T.white,overflowX:"hidden",maxWidth:"100vw"}} className="buygrid">
      <div className="step-content" style={{padding:"44px 52px 60px",borderRight:`1px solid ${T.border}`}}>
        {breadcrumbs}
        <p style={{fontSize:11,fontWeight:600,color:T.blue,textTransform:"uppercase",letterSpacing:"1px",marginBottom:6,fontFamily:"'DM Sans',sans-serif"}}>Step 3 of 5</p>
        <h1 className="responsive-title" style={{fontFamily:"'Sora',sans-serif",fontSize:28,fontWeight:700,color:T.text,letterSpacing:"-0.6px",lineHeight:1.15}}>Payment Method</h1>
        <p style={{fontSize:14,color:T.text2,marginTop:6,lineHeight:1.6,fontFamily:"'DM Sans',sans-serif"}}>Choose how you'd like to pay for your crypto.</p>

        <div style={{marginTop:32,display:"flex",flexDirection:"column",gap:14}}>
          {methods.map(({key,label,sub,meta,Icon,iconBg,iconColor,badge,badgeBg,badgeColor})=>{
            const active = paymentMethod === key;
            return (
              <div key={key} onClick={()=>setPaymentMethod(key)} className="method-card"
                style={{border:`1.5px solid ${active?T.blue:T.border}`,borderRadius:20,padding:"20px 22px",background:active?T.blueLight:T.white,cursor:"pointer",display:"flex",alignItems:"center",gap:18,transition:"all 0.18s",position:"relative"}}>
                {active && <div style={{position:"absolute",top:14,right:14,width:22,height:22,borderRadius:"50%",background:T.blue,display:"flex",alignItems:"center",justifyContent:"center"}}>{Ico.check("#fff")}</div>}
                <div style={{width:56,height:56,borderRadius:16,background:iconBg,display:"flex",alignItems:"center",justifyContent:"center",color:iconColor,flexShrink:0}}><Icon/></div>
                <div style={{flex:1,minWidth:0}}>
                  <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:4}}>
                    <p style={{fontFamily:"'Sora',sans-serif",fontSize:15,fontWeight:700,color:active?T.blue:T.text}}>{label}</p>
                    <span style={{fontSize:10,fontWeight:700,color:badgeColor,background:badgeBg,padding:"2px 8px",borderRadius:999,fontFamily:"'DM Sans',sans-serif"}}>{badge}</span>
                  </div>
                  <p style={{fontSize:13,color:active?"#3B5AA8":T.text2,lineHeight:1.5,fontFamily:"'DM Sans',sans-serif"}}>{sub}</p>
                  <p style={{fontSize:12,color:active?T.blue:T.text3,marginTop:6,fontWeight:500,fontFamily:"'DM Sans',sans-serif"}}>{meta}</p>
                </div>
              </div>
            );
          })}
        </div>

        <div style={{display:"flex",alignItems:"flex-start",gap:10,background:T.blueLight,borderRadius:14,padding:"14px 18px",marginTop:24}}>
          <Ico.info/>
          <p style={{fontSize:13,color:"#1A3A8A",lineHeight:1.6,fontFamily:"'DM Sans',sans-serif"}}>Regardless of payment method, crypto is delivered directly to your Cheeseball internal wallet once confirmed.</p>
        </div>

        <div className="actions-wrap" style={{display:"flex",gap:12,marginTop:24}}>
          <GhostBtn onClick={prevStep} style={{flex:1}}>← Back</GhostBtn>
          <CTA onClick={nextStep} disabled={!paymentMethod} style={{flex:2}}>Continue <Ico.arrow/></CTA>
        </div>
        <p style={{fontSize:12,textAlign:"center",color:T.text3,marginTop:14,fontFamily:"'DM Sans',sans-serif"}}>Prices may change slightly before the transaction is completed.</p>
      </div>
      <RightPanel payAmount={payAmount} receiveAmount={receiveAmount} rate={finalRate} selectedAsset={selectedAsset} expiryTime={expiryTime} step={3}/>
    </div>
  );
}
